### ISSUE TITLE
Update TargetFrameworks (remove 5.0, add 6.0 and 7.0)

### ISSUE THREAD

**Issue by MagicAndre1981** [MarkCiliaVincenti/AsyncKeyedLock#7]
Currently you [still support 5.0](https://github.com/MarkCiliaVincenti/AsyncKeyedLock/blob/b6e302f4af1e547858ba41920f416145a8d6b947/AsyncKeyedLock/AsyncKeyedLock.csproj#L4) which is out of support. Best is to remove it and add the supported 6.0 and 7.0.

**Comment by MarkCiliaVincenti** [comment]
Hi, this is not an issue.

This library uses ValueTask and the version that shipped up to .NET Core 3.1 had an unoptimized version. An optimization was done and was included since .NET 5.0.

Therefore the targetframework is there simply so that anything on .NET Standard 2.0 that came before .NET 5.0 needs to add the package System.Threading.Tasks.Extensions version 4.5.4 so that it gets the optimized code.

If you try to install this library on .NET 6.0 or .NET 7.0, it will work, without any problems, and will not require the dependency of System.Threading.Tasks.Extensions.

**Comment by MagicAndre1981** [comment]
.net standard is dead and Microsoft recommends to explicitly target for net .net versions

**Comment by MarkCiliaVincenti** [comment]
I'm sorry but you need to show me some advantages for this. The library currently works under all these implementations:

https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

I don't think I really need to stay naming them one by one and increasing the size of the build unless there is some very specific advantage that I'm not seeing.
